export const tagLabels = { clinical:'Clinical', medical:'Medical', leadership:'Leadership', education:'Education', qi:'Quality improvement', technical:'Technical', digital:'Digital', research:'Research', governance:'Governance', speaking:'Speaking' };
export const entryTypes = ['Role','Achievement','Project','Qualification','Education','Publication','Presentation','Committee','Skill'];
export const fontOptions = [
	['modern','Aptos / Calibri'],['arial','Arial / Helvetica'],['tahoma','Tahoma / Verdana'],['trebuchet','Trebuchet MS'],['century','Century Gothic'],['georgia','Georgia'],['cambria','Cambria'],['garamond','Garamond'],['palatino','Palatino'],['baskerville','Baskerville'],['times','Times New Roman']
];
export const fontStacks = { modern:'Aptos, Calibri, "Segoe UI", Arial, sans-serif', arial:'Arial, Helvetica, sans-serif', tahoma:'Tahoma, Verdana, "Segoe UI", sans-serif', century:'"Century Gothic", Futura, "Trebuchet MS", sans-serif', georgia:'Georgia, "Times New Roman", serif', cambria:'Cambria, Georgia, "Times New Roman", serif', garamond:'Garamond, "EB Garamond", Georgia, serif', palatino:'"Palatino Linotype", Palatino, "Book Antiqua", Georgia, serif', baskerville:'Baskerville, "Baskerville Old Face", "Times New Roman", serif', times:'"Times New Roman", Times, serif', trebuchet:'"Trebuchet MS", "Segoe UI", Arial, sans-serif' };
export const safeColour = (value='') => /^#[0-9a-f]{6}$/i.test(value) ? value : '#2563eb';
export const parseTags = (value='') => [...new Set((Array.isArray(value) ? value : value.split(',')).map(t=>t.trim().toLowerCase()).filter(Boolean))];
export function formatDate(value) { if (!value) return ''; const [y,m]=value.split('-'); return m ? new Date(Date.UTC(+y,+m-1,1)).toLocaleDateString('en-GB',{month:'short',year:'numeric'}) : y; }
export function formatDateRange(entry) { const start=formatDate(entry.startDate), end=entry.current?'Present':formatDate(entry.endDate); return start&&end?`${start} – ${end}`:end||start||''; }
export const shorten = (value,n) => value.length>n ? value.slice(0,n).replace(/\s+\S*$/,'')+'…' : value;
export function rankedEntries(entries, profile) { const tags=profile?.tags||[]; return entries.map(e=>({...e,score:(e.featured?5:0)+(e.tags||[]).filter(t=>tags.includes(t)).length*3+(e.profiles||[]).includes(profile?.id)*8})).filter(e=>e.score>0||!tags.length).sort((a,b)=>b.score-a.score||(b.endDate||'').localeCompare(a.endDate||'')); }
export function documentStyle(profile) { const s=profile?.documentStyle||{}; return { layout:['classic','contemporary','centred','minimal'].includes(s.layout)?s.layout:'classic', font:fontStacks[s.font]?s.font:'modern', textSize:Math.min(120,Math.max(85,Number(s.textSize)||100)), padding:Math.min(25,Math.max(10,Number(s.padding)||16)), sectionSpacing:Math.min(30,Math.max(6,Number(s.sectionSpacing)||14)), itemSpacing:Math.min(22,Math.max(3,Number(s.itemSpacing)||10)), paragraphSpacing:Math.min(14,Math.max(0,Number.isFinite(Number(s.paragraphSpacing))?Number(s.paragraphSpacing):3)), lineHeight:Math.min(1.7,Math.max(1.2,Number(s.lineHeight)||1.4)) }; }
export function validateImportFile(raw) { if(raw?.kind!=='career-canvas-import'||raw?.schemaVersion!==1||!raw.payload)throw new Error('Unsupported import format'); const p=raw.payload; if(p.profile&&typeof p.profile!=='object')throw new Error('Invalid profile'); if(p.cvProfiles&&!Array.isArray(p.cvProfiles))throw new Error('Invalid CV profiles'); if(p.entries&&!Array.isArray(p.entries))throw new Error('Invalid evidence records'); if(!p.profile&&!p.cvProfiles?.length&&!p.entries?.length)throw new Error('The import contains no data'); for(const item of [...(p.cvProfiles||[]),...(p.entries||[])])if(!item||typeof item!=='object'||typeof item.id!=='string'||!item.id.trim())throw new Error('Every imported record needs an ID'); if(JSON.stringify(raw).length>2*1024*1024)throw new Error('The import file is too large'); return p; }
export function mergeById(current,incoming,replace){const result=[...current];let added=0,updated=0,skipped=0;for(const item of incoming||[]){const i=result.findIndex(x=>x.id===item.id);if(i<0){result.push(item);added++;}else if(replace){result[i]=item;updated++;}else skipped++;}return{result,added,updated,skipped};}
