<script setup>
import { nextTick, onBeforeUnmount, onMounted, ref } from 'vue';
import AppHeader from './components/AppHeader.vue'; import EvidenceBank from './components/EvidenceBank.vue'; import ProfilesView from './components/ProfilesView.vue'; import CvPreview from './components/CvPreview.vue'; import EditorDialog from './components/EditorDialog.vue'; import TransferDialogs from './components/TransferDialogs.vue';
const data=ref(),activeView=ref('evidence'),selectedProfileId=ref(''),saveState=ref('Saved'),editor=ref(),transfer=ref(),toastMessage=ref(''),fatal=ref(false);let saveTimer,toastTimer;const edition=window.CareerCanvasEdition||{};
function showView(view){activeView.value=view;if(view==='preview'&&!selectedProfileId.value)selectedProfileId.value=data.value?.cvProfiles[0]?.id||'';}
function toast(message){toastMessage.value=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastMessage.value='',3500);}
function changed(){clearTimeout(saveTimer);saveState.value='Saving…';saveTimer=setTimeout(async()=>{try{const r=await fetch('/api/data',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(data.value)});if(!r.ok)throw new Error();saveState.value='Saved';}catch{saveState.value='Save failed';toast('Could not save. Download a backup before closing.');}},400);nextTick(()=>edition.afterRender?.({data:data.value}));}
function saveEditor({editing,value}){if(editing.kind==='identity')data.value.profile={...data.value.profile,...value};else{const key=editing.kind==='entry'?'entries':'cvProfiles',i=data.value[key].findIndex(x=>x.id===editing.id);if(i<0)data.value[key].push(value);else data.value[key][i]=value;}changed();}
function deleteEditor(editing){const key=editing.kind==='entry'?'entries':'cvProfiles';data.value[key]=data.value[key].filter(x=>x.id!==editing.id);changed();}
function replaceData(next){data.value=next;selectedProfileId.value=next.cvProfiles[0]?.id||'';changed();}
function preview(id){selectedProfileId.value=id;showView('preview');}
function printCv(){showView('preview');nextTick(()=>window.print());}
function keydown(e){if((e.ctrlKey||e.metaKey)&&e.key==='p'){e.preventDefault();printCv();}}
onMounted(async()=>{try{const r=await fetch('/api/data');if(!r.ok)throw new Error();data.value=await r.json();selectedProfileId.value=data.value.cvProfiles[0]?.id||'';window.addEventListener('keydown',keydown);await edition.start?.({getData:()=>data.value,setData:next=>{data.value=next;changed();},render:()=>nextTick(()=>edition.afterRender?.({data:data.value})),showView,toast});edition.afterRender?.({data:data.value});}catch{fatal.value=true;}});onBeforeUnmount(()=>window.removeEventListener('keydown',keydown));
</script>
<template><div v-if="fatal"><main class="fatal"><h1>Career Canvas could not start</h1><p>Check that the server can write to its data volume, then reload.</p></main></div><template v-else-if="data"><AppHeader :active-view="activeView" :save-state="saveState" @view="showView" @import="transfer.openImport()" @backup="transfer.openBackup()" @print="printCv"/><main><EvidenceBank v-if="activeView==='evidence'" :data="data" @edit-identity="editor.open('identity')" @edit-entry="id=>editor.open('entry',id)" @add-entry="editor.open('entry')"/><ProfilesView v-else-if="activeView==='profiles'" :data="data" @add-profile="editor.open('profile')" @edit-profile="id=>editor.open('profile',id)" @preview="preview"/><CvPreview v-else :data="data" :selected-id="selectedProfileId" @select="selectedProfileId=$event" @changed="changed" @print="printCv"/></main><footer class="app-credit" aria-label="Project attribution">Career Canvas was originally created by <strong>Thomas Johnson</strong>. <a href="https://github.com/jetbackwards/career-canvas" target="_blank" rel="noopener noreferrer">Source code</a><span aria-hidden="true">·</span>You may share it under the <a href="https://www.gnu.org/licenses/agpl-3.0.html" target="_blank" rel="noopener noreferrer">AGPL-3.0</a>; no warranty.</footer><EditorDialog ref="editor" :data="data" @save="saveEditor" @delete="deleteEditor"/><TransferDialogs ref="transfer" :data="data" @replace="replaceData" @changed="changed" @toast="toast"/><div id="toast" role="status" aria-live="polite" :class="{show:toastMessage}">{{ toastMessage }}</div></template></template>
