FROM node:22-alpine
WORKDIR /app

COPY package*.json ./

RUN --mount=type=cache,target=/root/.npm npm i

COPY vite.config.js ./
COPY client ./client
COPY public ./public

EXPOSE 5173

HEALTHCHECK --interval=2s --timeout=2s --start-period=5s --retries=30 \
  CMD wget --spider http://localhost:5173 || exit 1

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]