<script setup>
import { nextTick, reactive, ref } from 'vue'; import { entryTypes, parseTags } from '../lib/career.js';
const props=defineProps({data:Object}); const emit=defineEmits(['save','delete']); const dialog=ref(); const editing=reactive({kind:'',id:'',isNew:false}); const value=reactive({});
function reset(next){for(const key of Object.keys(value))delete value[key];Object.assign(value,next);}
async function open(kind,id){Object.assign(editing,{kind,id:id||crypto.randomUUID(),isNew:!id});if(kind==='identity')reset({...props.data.profile});if(kind==='entry')reset({...props.data.entries.find(x=>x.id===id)||{type:'Achievement',title:'',subtitle:'',organisation:'',startDate:'',endDate:'',current:false,summary:'',outcomes:'',tags:[],featured:false,profiles:[]},tags:(props.data.entries.find(x=>x.id===id)?.tags||[]).join(', ')});if(kind==='profile'){const p=props.data.cvProfiles.find(x=>x.id===id)||{name:'',title:'',summary:'',accent:'#2563eb',tags:[],maxPages:2};reset({...p,tags:(p.tags||[]).join(', ')});}await nextTick();dialog.value.showModal();}
function save(){const result={...value};if(editing.kind!=='identity')result.id=editing.id;if(editing.kind==='entry'){result.tags=parseTags(result.tags);result.current=!!result.current;result.featured=!!result.featured;if(result.current)result.endDate='';}if(editing.kind==='profile'){result.tags=parseTags(result.tags);result.maxPages=Number(result.maxPages)||2;}emit('save',{editing:{...editing},value:result});dialog.value.close();}
function remove(){if(confirm('Delete this record? This cannot be undone after it is saved.')){emit('delete',{...editing});dialog.value.close();}}
defineExpose({open});
</script>
<template><dialog ref="dialog"><form method="dialog" @submit.prevent="save"><div class="dialog-head"><div><p class="eyebrow">{{ editing.kind==='identity'?'MASTER PROFILE':editing.kind==='profile'?'CV PROFILE':'EVIDENCE' }}</p><h2>{{ editing.kind==='identity'?'Professional identity':editing.kind==='profile'?(editing.isNew?'New CV profile':'Edit CV profile'):(editing.isNew?'Add evidence':'Edit evidence') }}</h2></div><button type="button" class="icon-btn" aria-label="Close" @click="dialog.close()">×</button></div><div class="form-grid">
	<template v-if="editing.kind==='identity'"><label>Full name<input v-model="value.name"></label><label>Postnominals<input v-model="value.postnominals"></label><label>Professional headline<input v-model="value.headline"></label><label>Location<input v-model="value.location"></label><label>Email<input v-model="value.email" type="email"></label><label>Phone<input v-model="value.phone"></label><label>Links<input v-model="value.links"></label><label class="span-2">Master summary<textarea v-model="value.summary" rows="5"></textarea></label></template>
	<template v-else-if="editing.kind==='entry'"><label>Type<select v-model="value.type"><option v-for="type in entryTypes" :key="type">{{ type }}</option></select></label><label>Title<input v-model="value.title" required></label><label>Organisation<input v-model="value.organisation"></label><label>Supporting line<input v-model="value.subtitle"></label><label>Start date<input v-model="value.startDate" type="month"></label><label>End date<input v-model="value.endDate" type="month" :disabled="value.current"></label><label class="check span-2"><input v-model="value.current" type="checkbox">This is current — show the end date as Present</label><label class="span-2">Summary<textarea v-model="value.summary" rows="4"></textarea></label><label class="span-2">Outcomes — one per line<textarea v-model="value.outcomes" rows="4"></textarea></label><label class="span-2">Tags<input v-model="value.tags" placeholder="clinical, leadership, technical"></label><label class="check span-2"><input v-model="value.featured" type="checkbox">Treat as key evidence across profiles</label></template>
	<template v-else><label>Profile name<input v-model="value.name" required></label><label>Default CV title<input v-model="value.title"></label><label>Accent colour<input v-model="value.accent" type="color"></label><label>Target pages<input v-model.number="value.maxPages" type="number" min="1" max="5"></label><label class="span-2">Profile summary<textarea v-model="value.summary" rows="5"></textarea></label><label class="span-2">Priority tags<input v-model="value.tags" placeholder="technical, digital, leadership"></label></template>
	</div><div class="dialog-actions"><button v-if="editing.kind!=='identity'&&!editing.isNew" type="button" class="danger" @click="remove">Delete</button><span></span><button type="button" class="ghost" @click="dialog.close()">Cancel</button><button type="submit" class="primary">Save</button></div></form></dialog></template>
