<script setup>
import { reactive, ref } from 'vue'; import { mergeById, validateImportFile } from '../lib/career.js';
const props=defineProps({data:Object}); const emit=defineEmits(['replace','changed','toast']); const backup=ref(), importer=ref(); const pending=ref(); const preview=reactive({title:'',source:'',error:''}); const options=reactive({identity:true,profiles:true,entries:true,conflict:'keep'});
function openBackup(){backup.value.showModal();} function openImport(){pending.value=null;Object.assign(preview,{title:'',source:'',error:''});importer.value.showModal();}
function download(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(props.data,null,2)],{type:'application/json'}));a.download=`career-canvas-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);}
async function restore(event){const file=event.target.files[0];if(!file)return;try{const incoming=JSON.parse(await file.text());if(!incoming.profile||!Array.isArray(incoming.entries)||!Array.isArray(incoming.cvProfiles))throw new Error();if(!confirm(`Restore ${incoming.entries.length} evidence records and replace the current data?`))return;emit('replace',incoming);backup.value.close();emit('toast','Backup restored');}catch{emit('toast','That file is not a valid Career Canvas backup.');}finally{event.target.value='';}}
async function inspect(event){const file=event.target.files[0];if(!file)return;try{const raw=JSON.parse(await file.text()),payload=validateImportFile(raw);pending.value={raw,payload};Object.assign(preview,{title:raw.metadata?.title||file.name,source:raw.metadata?.source||'',error:''});}catch(error){pending.value=null;Object.assign(preview,{title:'Unable to use this file',source:'',error:error.message||'Invalid JSON file'});}}
function apply(){if(!pending.value)return;const p=pending.value.payload,replace=options.conflict==='replace',totals={added:0,updated:0,skipped:0};if(options.identity&&p.profile)for(const [k,v] of Object.entries(p.profile))if(replace||!props.data.profile[k])props.data.profile[k]=v;for(const [enabled,key] of [[options.profiles,'cvProfiles'],[options.entries,'entries']])if(enabled){const merged=mergeById(props.data[key],p[key],replace);props.data[key]=merged.result;for(const k of Object.keys(totals))totals[k]+=merged[k];}emit('changed');importer.value.close();emit('toast',`Import complete: ${totals.added} added, ${totals.updated} updated${totals.skipped?`, ${totals.skipped} kept`:''}.`);}
defineExpose({openBackup,openImport});
</script>
<template>
	<dialog ref="backup" id="backupDialog"><div class="dialog-head"><div><p class="eyebrow">PORTABLE DATA</p><h2>Backup and restore</h2></div><button class="icon-btn" @click="backup.close()">×</button></div><p>Download everything as JSON, or restore a previous Career Canvas backup.</p><div class="backup-actions"><button class="primary" @click="download">Download backup</button><label class="ghost file-label">Restore backup<input type="file" accept="application/json" @change="restore"></label></div></dialog>
	<dialog ref="importer" id="importDialog"><div class="dialog-head"><div><p class="eyebrow">ADD CAREER DATA</p><h2>Import records</h2></div><button class="icon-btn" aria-label="Close" @click="importer.close()">×</button></div><p class="dialog-copy">Import adds information to your current evidence bank. Unlike restore, it does not remove records that are not in the file.</p><label class="import-picker">Career Canvas import file<input type="file" accept="application/json" @change="inspect"></label>
		<div v-if="preview.title" class="import-preview"><strong>{{ preview.title }}</strong><p v-if="preview.source">Source: {{ preview.source }}</p><p v-if="preview.error">{{ preview.error }}</p><dl v-if="pending"><div><dt>{{ pending.payload.profile?1:0 }}</dt><dd>identity</dd></div><div><dt>{{ pending.payload.cvProfiles?.length||0 }}</dt><dd>CV profiles</dd></div><div><dt>{{ pending.payload.entries?.length||0 }}</dt><dd>evidence records</dd></div></dl></div>
		<div v-if="pending" class="import-options"><fieldset><legend>Include</legend><label class="check"><input v-model="options.identity" type="checkbox" :disabled="!pending.payload.profile">Professional identity</label><label class="check"><input v-model="options.profiles" type="checkbox" :disabled="!pending.payload.cvProfiles?.length">CV profiles</label><label class="check"><input v-model="options.entries" type="checkbox" :disabled="!pending.payload.entries?.length">Evidence records</label></fieldset><label>When an ID already exists<select v-model="options.conflict"><option value="keep">Keep my existing record</option><option value="replace">Use the imported record</option></select></label></div>
		<div class="dialog-actions import-actions"><span></span><span></span><button class="ghost" @click="importer.close()">Cancel</button><button class="primary" :disabled="!pending" @click="apply">Import data</button></div>
	</dialog>
</template>
